Readregion api change
sparkfun/SparkFun_Toolkit pull request #29
Opened 2023-12-13 23:01 UTC by SFE-Brudnerd

Adds in gitignore and gitattributes files.
Rework readRegisterRegion to return error type and have an output argument for the number of bytes read.
Makes default stop value false so as to not send a stop mid-read.
Make readRegisterRegion take in a reference rather than a pointer.
Rev to 0.9.0.

2023-12-13 23:07 UTC, SFE-Brudnerd commented
This matches most implementations of modern I2C devices. By sending a stop command after sending the device register address rather than a repeat start, you end the transaction early and leave the bus in an odd state. This corrects this and also corrects how the continued read of values in the `requestFrom` function operates. Prior to this, it would always send a stop if it was done, or send `stop()` (default to true, aka the same thing).

In ADS1219 datasheet:
![image](https://github.com/sparkfun/SparkFun_Toolkit/assets/101155592/bf7aaa85-2666-449a-8202-d68e3b67aa46)

In AS7331 datasheet:
![image](https://github.com/sparkfun/SparkFun_Toolkit/assets/101155592/8974fa70-bba5-4586-b91e-73f2708deb99)

In my experience this is the default behavior, and less capable devices should `setStop()` to true if they need it.

2023-12-14 08:03 UTC, PaulZC requested changes

2023-12-14 08:03 UTC, PaulZC commented on src/sfeTkArdSPI.cpp
> +    sfeTkError_t retval = readRegisterRegion(devReg, (uint8_t *)&data, sizeof(data), nRead);
Strictly, ```sizeof(data)``` should be ```sizeof(uint8_t)```

2023-12-14 08:03 UTC, PaulZC commented on src/sfeTkArdSPI.cpp
> +    return (retval == kSTkErrOk && nRead == sizeof(data) ? kSTkErrOk : retval);
Strictly, ```sizeof(data)``` should be ```sizeof(uint8_t)```

2023-12-14 08:03 UTC, PaulZC commented on src/sfeTkArdSPI.cpp
> +    sfeTkError_t retval = readRegisterRegion(devReg, (uint8_t *)&data, sizeof(data), nRead);
Strictly, ```sizeof(data)``` should be ```sizeof(uint16_t)```

2023-12-14 08:03 UTC, PaulZC commented on src/sfeTkArdSPI.cpp
> +    return (retval == kSTkErrOk && nRead == sizeof(data) ? kSTkErrOk : retval);
Strictly, ```sizeof(data)``` should be ```sizeof(uint16_t)```

2023-12-14 14:41 UTC, SFE-Brudnerd commented on src/sfeTk/sfeTkII2C.h
> +    sfeTkII2C() : _address{kNoAddress}, _stop{false}
Sounds good! I'll also add to the documentation to add the `setStop()` in to the interface-specific driver.

2023-12-14 14:44 UTC, SFE-Brudnerd commented on src/sfeTk/sfeTkII2C.h
> +    virtual bool stop(void)
In C/C++ true compiles to 1 and false compiles to 0, so it should be fine. Additionally in the AVR Wire.cpp file the void function sends a true. I think this should be fine.

```C++
//	This provides backwards compatibility with the original
//	definition, and expected behaviour, of endTransmission
//
uint8_t TwoWire::endTransmission(void)
{
  return endTransmission(true);
}
```

2023-12-14 15:08 UTC, SFE-Brudnerd commented
Should we use `readRegisterRegion` in `readRegisterByte()`?

2023-12-14 15:36 UTC, PaulZC approved these changes
Looking good!

Should we use region in byte? Nah... ;-)

2023-12-14 18:44 UTC, gigapod approved these changes
Looks good to me.

2023-12-14 18:44 UTC, merged